server:
    port: 8018
#  servlet:
#    session:
#      timeout: 6h

spring:
#  main:
#    web-application-type: none
#  security:
#    user:
#      name: user #设置默认登录用户名
#      password: 123456 #设置默认登录密码 不设置会在控制台打印出，默认用户名是user
  datasource:
#    url: jdbc:mysql://localhost:3306/block?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false
    url: jdbc:log4jdbc:mysql://localhost:3306/block?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false
#    username: root
#    password: 111111
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # springboot 2.0 整合了hikari ,据说这是目前性能最好的java数据库连接池
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
      username: root
      password: 111111
      pool-name: MyHikariCP # 连接池名称
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    database: mysql
    open-in-view: true

jwt:
  token-header-key: Authorization
  token-prefix: NonceToken
  token-expiration: 43200000 #12*60*60*1000 12小时
  token-secret: NonceJwtSecret
